Update to Nette 3.0-alpha
skaut/SkautisNette pull request #19
Opened 2018-03-17 10:52 UTC by JindrichPilar

Remove packages that are part of nette/nette from composer.json
Update to minimal version 7.1
Remove HHVM support https://github.com/nette/utils/issues/110
declare  strict types

2018-03-17 16:26 UTC, sinacek approved these changes

2018-03-17 17:50 UTC, xificurk requested changes

2018-03-17 17:50 UTC, xificurk commented on src/SkautisExtension.php
> +		if ($config['profiler'] && (class_exists(Debugger::class) || class_exists('Nette\Diagnostics\Debugger'))) {
`Nette\Diagnostics\Debugger` je možné odstranit - bylo to tam kvůli kompatibilitě s nějakýma archaickýma verzema.

2018-03-17 17:50 UTC, xificurk commented on src/SkautisExtension.php
> +	public function __call(string $name, array $args)
Magic metodu a i `_validateConfig()` je možné odstranit, tohle byl "backport" funkcionality, která chyběla ve starších verzích Nette.

2018-03-17 17:50 UTC, xificurk commented on src/Tracy/Panel.php
> +		if (!class_exists(Debugger::class) && class_exists('Nette\Diagnostics\Debugger')) {
Tento if-blok je taky jen kompatibilita s Nette 2.1 a je možné jej odstranit. Stačí ponechat to co je v `else` bloku.

2018-03-26 12:27 UTC, JindrichPilar commented
Diky za code review, upraveno.

2018-03-26 12:38 UTC, xificurk approved these changes
:+1: Díky!

2018-03-26 12:39 UTC, merged