Kompatibilita s PHP 7.2
skaut/SkautisNette pull request #20
Opened 2018-03-26 18:09 UTC by fmasa

2018-03-26 20:30 UTC, xificurk approved these changes

2018-03-27 07:47 UTC, xificurk commented
Tohle reálně znamená dropnutí podpory pro Nette <2.4, tzn. bude potřeba bumpnout minimální verze composer.json, odstranit testy proti starším verzím Nette a odstranit kód, který zajišťoval kompatibilitu mezi všemi verzemi Nette (lze se inspirovat, příp. cherry-pickovat z #17 ).

2018-03-27 07:56 UTC, fmasa commented
Spíše dropnutí `nette/utils` < 2.4 a Nette 2.1. Ostatní komponenty (`nette/di`) lze dál používat ve starších verzích. I když Nette drží spíše pseudo-BC.

2018-03-27 08:03 UTC, fmasa commented
Ale jsem jen pro drop nižších verzí :+1:

2018-03-27 09:08 UTC, fmasa commented
Rebasnuto, @xificurk můžeš na to mrknout?

2018-04-03 12:15 UTC, fmasa commented
@xificurk Můžeš mrknout a případně mergnout?

2018-04-04 08:44 UTC, xificurk requested changes
Skvělá práce, jen prosím ještě dvě drobnosti.

2018-04-04 08:44 UTC, xificurk commented on src/Tracy/Panel.php
> +		call_user_func([Tracy\Debugger::class, 'getBar'])->addPanel($this);
Použij tu prosím přímé volání statické metody místo `call_user_func`

2018-04-04 08:44 UTC, xificurk commented on src/Tracy/Panel.php
> +		return call_user_func([Tracy\Debugger::class, 'dump'], $object, TRUE);
Použij tu prosím přímé volání statické metody místo `call_user_func`

2018-04-04 08:49 UTC, fmasa commented
@xificurk Upravil jsem

2018-04-04 09:01 UTC, xificurk approved these changes

2018-04-04 09:02 UTC, merged