Adapter pro PSR-16 SimpleCache
skaut/SkautisNette pull request #24
Opened 2019-10-21 15:57 UTC by JindrichPilar

Kompabilita se Skautis 3.0 (pro #17)

2019-10-23 22:29 UTC, fmasa requested changes

2019-10-23 22:29 UTC, fmasa commented on src/Cache/CacheAdapter.php
> +        static function () use
Je toto chování žádoucí? Tohle totiž tu výchozí hodnotu uloží do cache, což by nastat nemělo. PSR to tak nepředepisuje, Symfony/Cache (, které má asi nejpoužívanější implementaci) [tak také nefunguje](https://github.com/symfony/cache/blob/634fdd75503607d5584632f17288405f24788eae/Psr16Cache.php#L83) ale hlavně je to IMO neočekávané chování.

Správně je IMO:
```php
try {
  return $this->cache->load($key) ?? $default;
} catch(Throwable $e) {
  throw new CacheException("Failed to load key '$key''", $exception);
}
```

2019-10-23 22:29 UTC, fmasa commented on src/Cache/CacheAdapter.php
> +      Debugger::log($exception);
Tohle bude vyžadovat přidání Tracy jako přímé závislosti (místo suggest, jako je to teď).

2019-10-23 22:29 UTC, fmasa commented on src/Cache/CacheAdapter.php
> +      return "{$ttl->s} seconds";
Tohle nebude fungovat, pokud interval nebude zadaný jako vteřiny (viz http://sandbox.onlinephpfunctions.com/code/9b1aeb187b8c4d9a211bde445cfeda743db333f9).
Je potřeba použít např. `(new DateTime())->add($ttl) ` (IIRC, Nette podporuje přímo předání `DateTimeInterface`)

2019-10-24 08:40 UTC, JindrichPilar commented on src/Cache/CacheAdapter.php
> +      return "{$ttl->s} seconds";
Diky, tohle mi uniklo.

2019-10-24 08:42 UTC, JindrichPilar commented on src/Cache/CacheAdapter.php
> +        static function () use
Máš pravdu, bude to tak pro už existující hodnotu a ne callback očekávanější chování.

2020-02-02 13:16 UTC, fmasa approved these changes
Pořád si myslím, že dává smysl přidat `tracy/tracy` jako přímo závislost, ale to se případně dá udělat v samostatném PR. Tohle už vypadá dobře :+1:

2020-02-03 16:06 UTC, JindrichPilar commented
I bez Tracy to funguje a splňuje požadavky PSR. Myslím si proto že to jako přímá závislost není nutné a nechal bych na uživateli jestli Tracy použije nebo ne.

2020-02-03 16:27 UTC, merged

2020-02-03 16:28 UTC, fmasa commented
To vůbec nepopírám, jen je to pořád implicitní závislost (na API Tracy, i když nelockujeme verzi). Minimálně bych tedy přidal conflict pro Tracy 3.0 (která zatím není) + do travisu run, kde zkusíme odebrat Tracy před testováním.